export const GRUPOS = [
	"ABDOME",
	"BICEPS",
	"COSTAS",
	"GLUTEOS",
	"MEMBROS SUPERIORES 1",
	"MEMBROS SUPERIORES 2",
	"MEMBROS INFERIORES GERAL",
	"MEMBROS SUPERIORES GERAL",
	"OMBROS",
	"PANTURRILHA",
	"PEITORAL",
	"POSTERIORES DE COXAS",
	"QUADS",
	"TRICEPS",
] as const;

export const TREINOS_OPCOES = [
	"Treino 1",
	"Treino 2",
	"Treino 3",
	"Treino 4",
	"Treino 5",
	"Treino 6",
] as const;

export const CICLOS_OPCOES = [
	"Ciclo 1",
	"Ciclo 2",
	"Ciclo 3",
	"Ciclo 4",
	"Ciclo 5",
	"Ciclo 6",
	"Ciclo 7",
	"Ciclo 8",
	"Ciclo 9",
	"Ciclo 10",
    "Ciclo 11",
    "Ciclo 12",
    "Ciclo 13",
    "Ciclo 14",
    "Ciclo 15",
    "Ciclo 16",
    "Ciclo 17",
    "Ciclo 18",
    "Ciclo 19",
    "Ciclo 20",
] as const;
