export const MAPEAMENTO_VIDEOS: Record<string, string> = {
	"Abdominal Declinado": "abd_declinado.gif",
	"Abdominal Máquina": "abd_maquina.gif",
	"Agachamento": "agachamento.gif",
	"Apoio": "apoio.gif",
	"Apoio Pé no banco": "apoio_pe_banco.gif",
	"Barra no Graviton": "barra_graviton.gif",
	"Cadeira Extensora": "cadeira_extensora.gif",
	"Crucifixo reto com halteres": "crucifixo_reto_alteres.gif",
	"Crucifixo Cross Over": "desenvolvimento_militar_sentado.gif",
	"Crucifixo com Halteres": "crucifixo_halteres.gif",
	"Crucifixo Invertido Máquina": "crucifixo_invertido_maquina.gif",
	"Desenvolvimento Militar Sentado": "crucifixo_cross_over.gif",
	"Desenvolvimento com Halteres": "desenvolvimento_halteres.gif",
	"Desenvolvimento Máquina": "desenvolvimento_maquina.gif",
	"Elevação Lateral Curvado": "elevacao_lateral_curvado.gif",
	"Elevação Frontal Alternado Sentado": "elevacao_frontal_alternado_sentado.gif",
	"Elevação Lateral": "elevacao_lateral.gif",
	"Flying Reto Alternado": "flying_reto_alternado.gif",
	"Levantamento Terra": "levantamento_terra.gif",
	"Leg 45º": "leg_horizontal.gif",
	"Leg Horizontal": "leg_horizontal.gif",
	"Martelo Alternado": "martelo_alternado.gif",
	"Paralela Máquina": "paralela_maquina.gif",
	"Pull Down Articulado": "pulldown_articulado.gif",
	"Pull Down com Barra": "pulldown_barra.gif",
	"Puxador Frente": "puxador_frente.gif",
	"Remada Alta com Barra": "remada_alta_barra.gif",
	"Remada Sentada com Triangulo": "remada_sentada_triangulo.gif",
	"Rosca Direta Barra 'W'": "rosca_direta_w.gif",
	"Rosca Testa Halteres": "rosca_testa_halteres.gif",
	"Rosca Francesa Halteres": "rosca_francesa_halteres.gif",
	"Rosca Testa com Barra": "rosca_testa_barra.gif",
	"Supino Máquina": "supino_maquina.gif",
	"Supino Inclinado": "supino_inclinado.gif",
	"Supino Reto": "supino_reto.gif",
	"Triceps Pulley com Barra": "triceps_pulley_barra.gif",
	"Triceps Pulley com Corda": "triceps_pulley_corda.gif",
	"Triceps Pulley Unilateral": "triceps_pulley_unilateral.gif",
	"_Producao": "producao.gif",
};

export const GRUPOS = [
	"ABDOME",
	"BICEPS",
	"COSTAS",
	"GLUTEOS",
	"MEMBROS SUPERIORES 1",
	"MEMBROS SUPERIORES 2",
	"MEMBROS INFERIORES GERAL",
	"MEMBROS SUPERIORES GERAL",
	"OMBROS",
	"PANTURRILHA",
	"PEITORAL",
	"POSTERIORES DE COXAS",
	"QUADS",
	"TRICEPS",
] as const;

export const TREINOS_OPCOES = [
	"Treino 1",
	"Treino 2",
	"Treino 3",
	"Treino 4",
	"Treino 5",
	"Treino 6",
] as const;

export const CICLOS_OPCOES = [
	"Ciclo 1",
	"Ciclo 2",
	"Ciclo 3",
	"Ciclo 4",
	"Ciclo 5",
	"Ciclo 6",
	"Ciclo 7",
	"Ciclo 8",
	"Ciclo 9",
	"Ciclo 10",
] as const;
